name: Running tests
'on':
  push:
    branches:
      - production
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && npm ci && npm build 
      - run: npm i -D jest && npm run test
